name: Node CI

on:
  push:
    branches:
      - master
      - release/*
jobs:
  test:
    - uses: actions/checkout@v1
    - name: setup
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and test
      run: |
        npm ci
        npm test
      env:
        CI: true
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.PROJECT_NAME}}
          APPLICATION_CREDENTIALS: ${{secrets.GCLOUD_AUTH}}
        with:
          args: app deploy app.yaml
