name: Node CI

on:
  push:
    branches:
      - master
      - release/*
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      with:
        node-version: 12.x
      - name: npm install, lint, and test
        run: |
          npm lint
          npm ci
          npm test
        env:
          CI: true
      - uses: actions-hub/gcloud@master
        env:
          PROJECT_ID: ${{secrets.PROJECT_NAME}}
          APPLICATION_CREDENTIALS: ${{secrets.GCLOUD_AUTH}}
        with:
          args: app deploy app.yaml
